# python/m5/tools/html.py
"""Render the weekly newsletter Markdown into a styled, sanitized HTML page.

Belongs to the main agent. The HTML shell is a fixed, trusted template; the
newsletter body is derived from untrusted web-search text, so it is run through
an allowlist sanitizer (nh3) before it goes into the page — stripping any
<script>, onerror=, etc. that a search result might have smuggled in.
"""

from __future__ import annotations

import markdown as md
import nh3
from langchain_core.tools import tool

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }}
  h1 {{ font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }}
  h2 {{ color: #006DDD; margin-top: 1.6em; }}
  footer {{ margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
{body}
<footer>Generated by the Chinook Sales Assistant.</footer>
</body>
</html>"""


@tool
def markdown_to_html(markdown_text: str, title: str = "This Week in Music") -> str:
    """Convert a Markdown newsletter into a complete, styled HTML page.
    Returns the full HTML document as a string."""
    body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    # The body is built from untrusted web search, so allowlist-sanitize it
    # before rendering. The template itself is trusted and left intact.
    body = nh3.clean(body)
    return _HTML_TEMPLATE.format(title=title, body=body)
